### PR TITLE
scrollEventThrottle

### PR DESCRIPTION
**Pull request by Wari-Dudafa**

### CODE REVIEW

**Comment by Abhinandan-Kushwaha** [comment]
Thanks for the PR.
ScrollView has been removed from the file LineChart.tsx
However, I fill it's nice to have a scrollEventThrottle. I will add it at the right place.

**Comment by Abhinandan-Kushwaha** [comment]
Yes @rxnveer we are still using the ScrollView. It's just that I cannot accept this PR because as a part of the next release changes, I will be moving the ScrollView from LineChart.tsx to a common component.
Thanks for suggesting to expose the `scrollEventThrottle` as a prop. I will add this prop in the next release.

**Comment by rxnveer** [comment]
Sounds good, thanks @Abhinandan-Kushwaha :)

Looking forward to the next release.

**Comment by hstaudacher** [comment]
The last release was just a couple days ago without the property being exposed. Has this slipped?

**Comment by Abhinandan-Kushwaha** [comment]
@hstaudacher we missed it in this release. Please raise a PR

**Comment by Abhinandan-Kushwaha** [comment]
@Wari-Dudafa Can you please raise a new PR. People are waiting for this feature!

**Pull request closed without merging**
