### PR TITLE
Fix: remove all type errors

### PR DESCRIPTION
**Pull request by cliveportman**
After using this library, our project is failing because if the type errors in this library. This PR fixes all the errors, generally just by adding type `any` (or type `number` where it's obviously a number).

### CODE REVIEW

**Comment by Abhinandan-Kushwaha** [comment]
Hi @cliveportman 
Thanks for this much needed PR. I will merge it soon.

**Comment by SalesKnL** [comment]
@Abhinandan-Kushwaha Can it be merged?

**Comment by ygnoh** [comment]
@Abhinandan-Kushwaha Can it be merged?

**Comment by khunshan85** [comment]
@Abhinandan-Kushwaha When it can be merged? We are using this package in our application

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ygnoh 
I'm sorry for not getting back to you sooner. Can you pull the latest `master` and resolve the merge conflicts? I will review it asap.

**Comment by SalesKnL** [comment]
I'm not the author so I can't. @cliveportman could you do that please?

**Comment by ygnoh** [comment]
I'm not the author so I can't. @cliveportman could you do that please?

**Comment by cliveportman** [comment]
@Abhinandan-Kushwaha @ygnoh 

After fixing the conflicts, there are new type errors introduced by the use of non-existing props from gifted-chart-core. I need those fixing first, please. If you pull my branch and look at `/src/LineChart/index.tsx` you'll see what I'm referring to.

**Comment by Abhinandan-Kushwaha** [comment]
@cliveportman If possible, can you push the partial fix. I will add the rest of the types after merging yours.

**Comment by cliveportman** [comment]
@Abhinandan-Kushwaha Merge conflicts are now fixed - that's all I have time for at the moment. Will that do you?

**Review by Abhinandan-Kushwaha — APPROVED** [review]

**Comment by Abhinandan-Kushwaha** [comment]
Thanks a lot @cliveportman your PR is merged. I will release version `1.4.17` with your changes soon.

**Pull request merged**
